Droga5\OptimismBiasBundle\Entity\OptimismBiasSlice:
    type: entity
    table: null
    fields:
        isShareable:
            type: boolean
        linkedInDescription:
            type: string
            length: 200
            nullable: true
        linkedInTitle:
            type: string
            length: 70
            nullable: true
        linkedInUrl:
            type: text
            nullable: true
        ogCaption:
            type: string
            length: 70
            nullable: true
        ogDescription:
            type: string
            length: 200
            nullable: true
        ogImageUrl:
            type: text
            nullable: true
        ogTitle:
            type: string
            length: 70
            nullable: true
        ogUrl:
            type: text
            nullable: true
        themeId:
            type: integer
        twitterHashtags:
            type: string
            length: 70
            nullable: true
        twitterText:
            type: string
            length: 140
            nullable: true
        twitterUrl:
            type: text
            nullable: true
        isForestView:
            type: boolean
            nullable: true
        forestView1:
            type: integer
            nullable: true
        forestView2:
            type: integer
            nullable: true
        forestView3:
            type: integer
            nullable: true
        forestViewTitle:
            type: string
            nullable: true